name = "pos-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Cloudflare D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "pos_database"
database_id = "f76d66b5-3c71-4d46-9a1c-2d24c191bb8e"
